#!/bin/sh
#
# FLA Configuration Management init script. This script is designed to run
# from init on a System V style machine.  Put it in the inittab for level
# 3 and if you have ondemand levels put it in one of those too.
#
# Copyright:: Copyright 2006, Responsys, Inc.
# Original Author:: Grier Johnson <gjohnson@responsys.com>
#
#    This file is part of FLACM.
#
#    FLACM is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    FLACM is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# Last modification:: $Date: 2008-03-19 16:12:24 -0700 (Wed, 19 Mar 2008) $

# Declare the path we want
PATH="/bin:/sbin:/usr/bin:/usr/sbin:/opt/bin:/opt/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/sfw/bin"
FLACMDIR="/opt/flacm"
FLACMBIN="config-flacm"
SLEEPFILE="/tmp/.flacm.sleep"
IGNOREFILE="/var/flacm/.ignore"
# The gold server is different for each domain
GOLDSERV="http://flacm"
# Retry interval in seconds
RETRY=30
# Redirect STDOUT and STDERR to /dev/null
exec 1>/dev/null 2>&1

if [ -f $SLEEPFILE ]; then
  rm $SLEEPFILE
  sleep $RETRY
fi

# Respect the ignore file in the event that we're 
while [ -f $IGNOREFILE ]; do
  sleep 1
done

# Clean up failed flacm root
rm -rf /tmp/flacm[0-9][0-9][0-9]*
rm -rf /tmp/fix[0-9][0-9][0-9]*
rm -f /var/flacm/.starttime

# Look for wget in the path
WGET=`type -p wget`
if [ $? -ne 0 ]; then
  # This takes forever so we only run it if type doesn't work
  WGET=`find / -type f -name "wget" -print`
fi


# Set (quietly) execfail so we don't lose our shell if flacm fails
shopt -qs execfail

# Loop until we exec flacm properly
while (true)
do
  if [ ! -e $FLACMDIR ]; then
    mkdir -p $FLACMDIR
  elif [ ! -d $FLACMDIR ]; then
    rm -f $FLACMDIR
    mkdir -p $FLACMDIR
  fi
  cd $FLACMDIR
  if [ -f $FLACMBIN ]; then
    CHECKFLACM=1
    if [ -f ${FLACMBIN}.1 ]; then
      rm -f ${FLACMBIN}.1
    fi
  fi
  $WGET $GOLDSERV/$FLACMBIN

  if [ $CHECKFLACM ]; then
    diff -q $FLACMBIN ${FLACMBIN}.1
    if [ $? -ne 0 ]; then
      mv ${FLACMBIN}.1 $FLACMBIN
    else
      rm -f ${FLACMBIN}.1
    fi
  fi

  chmod 750 $FLACMBIN

  if [ $? -eq 0 ]; then
    touch $SLEEPFILE
    export FLACMDIR
    export GOLDSERV
    export WGET
    exec $FLACMDIR/$FLACMBIN
  fi
done
